### ISSUE TITLE
Transition Aborted Error

### ISSUE THREAD

**Issue by ehubbell** [boundless-inc/ember-cli-bs-pagination#5] opened 2018-08-15 23:28 UTC
Hey There,

I'm getting a`TransitionAbortedError` when I click through the pagination on all my routes. Pagination still works and the user doesn't get interrupted by this but I'd still like to eliminate the error. Any idea what would cause this? I'm using `ember-fastboot` too if that makes a difference. 

Here's my route:

```
	// Properties
	queryParams: {
		page: { refreshModel: true },
		page_size: { refreshModel: true }
	},

	// Hooks	
	model(params) {
		let business = this.modelFor('admin');
		return RSVP.hash({
			model: this.store.adapterFor('booking').getBusinessBookings(business, params),
			business: business,
		});
	},
```

Here's my template:

```
{{#if (gt model.meta.pagination.pages 1)}}
	<section class='admin-pagination'>
		<div class='row'>
			<div class='col-12'>
				{{page-numbers 
					page=page 
					additionalClasses='justify-content-center'
					totalPages=model.meta.pagination.pages
				}}
			</div>
		</div>
	</section>
{{/if}}
```

And my `{{page-numbers}}` template:

```
<ul class="pagination {{additionalClasses}}">
  <li class="page-item {{unless canStepBackward 'disabled'}}">
    {{#if canStepBackward}}
      <a class="page-link" href={{previousPageUrl}} onclick={{action 'decrementPage'}}>
      	<i class='fa small fa-chevron-left'></i>
      </a>
    {{else}}
      <span class="page-link">
      	<i class='fa small fa-chevron-left'></i>
      </span>
    {{/if}}
  </li>
  {{#each pageItems as |pageItem index|}}
    <li class="page-item {{if pageItem.current 'active' ''}}">
      {{#if pageItem.current}}
        <span class="page-link">
          {{pageItem.number}}<span class="sr-only">(current)</span>
        </span>
      {{else}}
        <a class="page-link" href="{{pageItem.url}}" onclick={{action 'setPage' pageItem.number}}>{{pageItem.number}}</a>
      {{/if}}
    </li>
  {{/each}}
  <li class="page-item {{unless canStepForward 'disabled'}}">
    {{#if canStepForward}}
      <a class="page-link" href={{nextPageUrl}} onclick={{action 'incrementPage'}}>
      	<i class='fa small fa-chevron-right'></i>
      </a>
    {{else}}
      <span class="page-link">
      	<i class='fa small fa-chevron-right'></i>
      </span>
    {{/if}}
  </li>
</ul>
```

**Comment by sdhull** [comment] 2018-08-21 22:13
Hi @ehubbell! We haven't encountered that error while clicking through pagination links, so off the top of my head I'm not entirely certain.

Out of curiosity, if you add an `afterModel()` hook with `console.log('loaded model')` in there, can you verify that you click on the next page _after_ the current page has loaded? My guess is that you click `2` then `3` before `2` has completed loading, so it naturally aborts the transition for page `2`.

If you can reproduce in https://ember-twiddle.com/ I can take a look

**Comment by sdhull** [comment] 2018-08-22 02:08
Some more digging turned up an [open issue](https://github.com/emberjs/ember.js/issues/12505) in ember about this. Looks like our error reporting (rollbar) is not automatically reporting errors from `Ember.RSVP` (and we hadn't subscribed to them), so that's why we were blissfully ignorant of this happening.

AFAICT from that issue, most people are currently just explicitly ignoring that error. If you're using Sentry, it looks like it should be ignoring it for you automatically.

I'm going to close this as it seems like a problem with ember and not the addon.

**Closed by sdhull** 2018-08-22 02:08 UTC

**Comment by ehubbell** [comment] 2018-08-22 13:13
@sdhull thanks for getting back to me and digging into this :) Yeah, I've been catching this error via Honeybadger error tracking. I implemented one of the code snippets to ignore em for now. Thanks again!
